# Nombres de archivos
TARGET = main.static.exe
LIBRARY = libucsp.a
OBJECTS = main.o libucsp.o

# Reglas de compilación
all: $(TARGET)

libucsp.o: ucsp.c ucsp.h
	gcc -c ucsp.c -o libucsp.o

# Crear la biblioteca estática
$(LIBRARY): libucsp.o
	ar rcs $(LIBRARY) libucsp.o

# Enlazar y crear el ejecutable
$(TARGET): $(OBJECTS) $(LIBRARY)
	gcc -o $(TARGET) main.o -L. $(LIBRARY)

# Limpiar los archivos compilados
clean:
	rm -f $(OBJECTS) $(TARGET) $(LIBRARY)


